name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      # not needed for linting
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run check

  Test:
    runs-on: ubuntu-latest
    env:
      # opt into the hermetic install and place binaries in the local folder
      # https://playwright.dev/docs/browsers#managing-browser-binaries-1
      PLAYWRIGHT_BROWSERS_PATH: '0'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npx playwright install
      - run: npm test
