name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check
        run: npm run check

  Test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - name: Install dependencies
        id: install_dependencies
        run: |
          npm ci
          echo "::set-output name=playwright_version::$(npx playwright --version)"
      - name: Set Playwright browsers path
        run: echo PLAYWRIGHT_BROWSERS_PATH=$RUNNER_TEMP/playwright_browsers >> $GITHUB_ENV
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }} - Playwright ${{ steps.install_dependencies.outputs.playwright_version }} browsers
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Test
        run: npx playwright test
